// <auto-generated />
using CityInfo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityInfo.Data.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20190903185017_AddTestData")]
    partial class AddTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityInfo.Data.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Population");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Places");

                    b.HasData(
                        new { Id = 1, Name = "London", Population = 0, TypeId = 1 },
                        new { Id = 2, Name = "Aberdeen", Population = 0, TypeId = 1 },
                        new { Id = 3, Name = "Barnsley", Population = 0, TypeId = 2 },
                        new { Id = 4, Name = "Barking", Population = 0, TypeId = 2 },
                        new { Id = 5, Name = "Carlisle", Population = 0, TypeId = 1 }
                    );
                });

            modelBuilder.Entity("CityInfo.Data.Entities.PlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PlaceType");

                    b.HasData(
                        new { Id = 1, Name = "City" },
                        new { Id = 2, Name = "Town" },
                        new { Id = 3, Name = "Village" }
                    );
                });

            modelBuilder.Entity("CityInfo.Data.Entities.Place", b =>
                {
                    b.HasOne("CityInfo.Data.Entities.PlaceType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
